[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/v5/config"
  to = "/.netlify/functions/platform_config"
  status = 200

[[redirects]]
  from = "/api/v5/schedules"
  to = "/.netlify/functions/platform_schedules"
  status = 200

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
